Bug Fix - Rename "button" folder to avoid conflict with "espressif__button" component (#452)
* button: rename folder to avoid conflict with "espressif__button" component

When adding the "espressif/button" component, build error occured.
Two different errors are reported (depending how the component is added).

Error 1:
CMake Error at C:/Users/<username>/.platformio/packages/framework-espidf/tools/cmake/component.cmake:479 (add_library):
  Target "__idf_button" links to itself.

Error 2:
CMake Error at C:/Users/<username>/.platformio/packages/framework-espidf/tools/cmake/component.cmake:250 (message):
  ERROR: Cannot process component requirements.  Multiple candidates to
  satisfy project requirements:

    requirement: "button" candidates: "espressif__button, button"

Renamed the button folder to avoid the conflict with the "espressif__button" component.

Signed-off-by: Sylvain Lemieux <sylemieux.git@gmail.com>

* watcher: update include file path

Update "watcher.hpp" include path to match the new folder name.

Signed-off-by: Sylvain Lemieux <sylemieux.git@gmail.com>

* badge: update include file path

Update "watcher.hpp" include path to match the new folder name.

Signed-off-by: Sylvain Lemieux <sylemieux.git@gmail.com>

---------

Signed-off-by: Sylvain Lemieux <sylemieux.git@gmail.com>
Co-authored-by: Sylvain Lemieux <sylemieux.git@gmail.com>